--- USERS_TBL
ALTER TABLE USERS_TBL DROP PRIMARY KEY;
ALTER TABLE USERS_TBL DROP CONSTRAINT IF EXISTS NN_USERS_NAME;
ALTER TABLE USERS_TBL DROP CONSTRAINT IF EXISTS NN_USERS_LASTNAME1;
ALTER TABLE USERS_TBL DROP CONSTRAINT IF EXISTS NN_USERS_EMAIL;
ALTER TABLE USERS_TBL DROP INDEX IF EXISTS U_USERS_EMAIL;

ALTER TABLE USERS_TBL ADD CONSTRAINT PK_USERS_TBL PRIMARY KEY (ID);
ALTER TABLE USERS_TBL ADD CONSTRAINT NN_USERS_NAME CHECK(NAME IS NOT NULL);
ALTER TABLE USERS_TBL ADD CONSTRAINT NN_USERS_LASTNAME1 CHECK(LASTNAME1 IS NOT NULL);
ALTER TABLE USERS_TBL ADD CONSTRAINT NN_USERS_EMAIL CHECK(EMAIL IS NOT NULL);
ALTER TABLE USERS_TBL ADD CONSTRAINT U_USERS_EMAIL UNIQUE (EMAIL);

SHOW CREATE TABLE USERS_TBL;

--- STARS_TBL
ALTER TABLE STARS_TBL DROP PRIMARY KEY;
ALTER TABLE STARS_TBL DROP CONSTRAINT IF EXISTS NN_STARS_NAME;
ALTER TABLE STARS_TBL DROP INDEX IF EXISTS U_STARS_NAME;

ALTER TABLE STARS_TBL ADD CONSTRAINT PK_STARS_TBL PRIMARY KEY (ID);
ALTER TABLE STARS_TBL ADD CONSTRAINT NN_STARS_NAME CHECK(NAME IS NOT NULL);
ALTER TABLE STARS_TBL ADD CONSTRAINT U_STARS_NAME UNIQUE (NAME);
ALTER TABLE STARS_TBL MODIFY ID INTEGER AUTO_INCREMENT;

SHOW CREATE TABLE STARS_TBL;

--- USERS_STARS_TBL
ALTER TABLE USERS_STARS_TBL DROP PRIMARY KEY;
ALTER TABLE USERS_STARS_TBL DROP FOREIGN KEY IF EXISTS FK_USERS_STARS_SENDER_ID;
ALTER TABLE USERS_STARS_TBL DROP FOREIGN KEY IF EXISTS FK_USERS_STARS_RECEIVER_ID;
ALTER TABLE USERS_STARS_TBL DROP FOREIGN KEY IF EXISTS FK_USERS_STARS_STAR_ID;
ALTER TABLE USERS_STARS_TBL DROP KEY IF EXISTS FK_USERS_STARS_SENDER_ID;
ALTER TABLE USERS_STARS_TBL DROP KEY IF EXISTS FK_USERS_STARS_RECEIVER_ID;
ALTER TABLE USERS_STARS_TBL DROP KEY IF EXISTS FK_USERS_STARS_STAR_ID;

ALTER TABLE USERS_STARS_TBL ADD CONSTRAINT PK_USERS_STARS_TBL PRIMARY KEY (ID);
ALTER TABLE USERS_STARS_TBL ADD CONSTRAINT FK_USERS_STARS_SENDER_ID FOREIGN KEY (SENDER_ID) REFERENCES USERS_TBL (ID);
ALTER TABLE USERS_STARS_TBL ADD CONSTRAINT FK_USERS_STARS_RECEIVER_ID FOREIGN KEY (RECEIVER_ID) REFERENCES USERS_TBL (ID);
ALTER TABLE USERS_STARS_TBL ADD CONSTRAINT FK_USERS_STARS_STAR_ID FOREIGN KEY (STAR_ID) REFERENCES STARS_TBL (ID);
ALTER TABLE USERS_STARS_TBL MODIFY ID INTEGER AUTO_INCREMENT;

SHOW CREATE TABLE USERS_STARS_TBL;
