DROP TABLE IF EXISTS USERS_TBL;
DROP TABLE IF EXISTS STARS_TBL;
DROP TABLE IF EXISTS USERS_STARS_TBL;

CREATE TABLE USERS_TBL (
  ID VARCHAR(60),
  EMAIL VARCHAR(60),
  NAME VARCHAR(60),
  LASTNAME1 VARCHAR(60),
  LASTNAME2 VARCHAR(60)
);

CREATE TABLE STARS_TBL (
  ID INTEGER,
  NAME VARCHAR(60),
  DESCRIPTION VARCHAR(60)
);

CREATE TABLE USERS_STARS_TBL (
  ID INTEGER,
  SENDER_ID VARCHAR(60),
  RECEIVER_ID VARCHAR(60),
  STAR_ID INTEGER,
  DESCRIPTION VARCHAR(60)
);

