--- USERS_TBL
INSERT INTO USERS_TBL (ID, EMAIL, NAME, LASTNAME1, LASTNAME2) VALUES ('1152455906', 'cristianhoyos66@gmail.com', 'Cristian', 'Hoyos', 'Jaramillo');

--- STARS_TBL
INSERT INTO STARS_TBL (NAME) VALUES ('Excelencia');
INSERT INTO STARS_TBL (NAME) VALUES ('Trabajo en Equipo');
INSERT INTO STARS_TBL (NAME) VALUES ('Pensar en Grande');
INSERT INTO STARS_TBL (NAME) VALUES ('Innovación Constante');
INSERT INTO STARS_TBL (NAME) VALUES ('Diversión');
INSERT INTO STARS_TBL (NAME) VALUES ('Actuar con Ética');
