--- USERS_TBL
INSERT INTO USERS_TBL (ID, EMAIL, NAME, LASTNAME1, LASTNAME2) VALUES ('1152455906', 'cristianhoyos66@gmail.com', 'Cristian', 'Hoyos', 'Jaramillo');
INSERT INTO USERS_TBL (ID, EMAIL, NAME, LASTNAME1, LASTNAME2) VALUES ('1234567891', 'cris66@gmail.com', 'Cris', 'Hoyos', 'Jaramillo');

--- STARS_TBL
INSERT INTO STARS_TBL (NAME) VALUES ('Excelencia');
INSERT INTO STARS_TBL (NAME) VALUES ('Trabajo en Equipo');
INSERT INTO STARS_TBL (NAME) VALUES ('Pensar en Grande');
INSERT INTO STARS_TBL (NAME) VALUES ('Innovación Constante');
INSERT INTO STARS_TBL (NAME) VALUES ('Diversión');
INSERT INTO STARS_TBL (NAME) VALUES ('Actuar con Ética');

--- USERS_STARS_TBL
INSERT INTO USERS_STARS_TBL (SENDER_ID, RECEIVER_ID, STAR_ID, DESCRIPTION) VALUES ('1152455906', '1234567891', 1, 'Thanks for all!');
INSERT INTO USERS_STARS_TBL (SENDER_ID, RECEIVER_ID, STAR_ID, DESCRIPTION) VALUES ('1234567891', '1152455906', 1, 'Thanks for all!');

